excluded:
  - .git
  - "**/.build"
  - "**/Package.swift"
  - "**/vendor"
  - "**/spec"

opt_in_rules:
  - sorted_imports
  - missing_docs
  - convenience_type
  - multiline_parameters
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - if_let_shadowing

disabled_rules:
  - orphaned_doc_comment
  - blanket_disable_command
  - unused_closure_parameter

identifier_name:
  max_length:
    warning: 60
    error: 80

large_tuple:
  warning: 4
  error: 5

missing_docs:
  excludes_inherited_types: false
