version: 2.1

orbs:
  revenuecat: revenuecat/sdks-common-config@2.2.0
  node: circleci/node@5.1.0

aliases:
  syncing-branches: &syncing-branches
    filters:
      tags:
        ignore: /.*/
      branches:
        only: /^sync\/.*/
  non-syncing-branches: &non-syncing-branches
    filters:
      tags:
        ignore: /.*/
      branches:
        ignore: /^sync\/.*/

commands:
  setup-git-credentials:
    steps:
      - run:
          name: Setup Git config
          command: |
            git config user.email $GIT_EMAIL
            git config user.name $GIT_USERNAME

  trust-github-key:
    steps:
      - run:
          name: Trust GitHub key
          command: |
            for ip in $(dig @8.8.8.8 github.com +short); \
            do ssh-keyscan github.com,$ip; \
            ssh-keyscan $ip; \
            done 2>/dev/null >> ~/.ssh/known_hosts

jobs:
  preview-docs:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - run:
          name: Render modified docs
          command: bundle exec fastlane preview_rendered_docs
      - store_artifacts:
          path: temp
          destination: temp
      - run:
          name: Post artifacts as comment
          command: bundle exec fastlane post_circleci_artifacts

  check-rendering:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - run:
          name: Check rendered docs can render
          command: bundle exec fastlane embed_code_blocks

  check-categories:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - run:
          name: Check rendered docs have categories
          command: bundle exec fastlane check_docs_categories

  sync-files-to-readme:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - when:
          condition:
            equal: [ /^sync\/.*/, << pipeline.git.branch >> ]
          steps:
            - node/install:
                install-yarn: false
                node-version: "16.13.1"
            - revenuecat/install-gem-unix-dependencies:
                cache-version: v1
            - run:
                name: Install rdme
                command: npm install -g rdme@8.6.4
            - run:
                name: Syncing files to Readme
                command: |
                  bundle exec fastlane sync_files_to_readme readme_api_key:$README_API_KEY

  open-syncing-pr:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - setup-git-credentials
      - trust-github-key
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - run:
          name: Render docs
          command: |
            bundle exec fastlane open_syncing_pr github_pr_token:$GITHUB_TOKEN readme_api_key:$README_API_KEY


workflows:
  version: 2

  open-syncing-pr:
    jobs:
      - open-syncing-pr:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: main

  sync:
    jobs:
      - check-categories: *syncing-branches
      - manual-approval-to-sync-with-readme:
          type: approval
          requires:
            - check-categories
          <<: *syncing-branches
      - sync-files-to-readme:
          requires:
            - hold
          <<: *syncing-branches

  no-op-sync:
    jobs:
      - sync-files-to-readme: *non-syncing-branches

  test:
    jobs:
      - check-rendering: *non-syncing-branches
      - preview-docs: *non-syncing-branches
