version: 2.1

orbs:
  revenuecat: revenuecat/sdks-common-config@2.2.0

jobs:
  check-files:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - run:
          name: Check rendered docs are safe to sync
          command: bundle exec fastlane check_docs

workflows:
  version: 2
  check-files:
    jobs:
      - check-files