# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Install dependencies"
lane :bootstrap do
    sh "npm", "install", "-g", "rdme"
    sh "npm", "install", "-g", "embedme"
end

desc "Description of what the lane does"
lane :render_docs do
    copy_docs_source_to_render_folder
    files_to_render = Dir.glob("rendered_docs/*.md")
    files_to_render.each do |file|
        render_markdown_file(file)
    end
    sync_files_to_readme
end

lane :copy_docs_source_to_render_folder do
    source_folder = "docs_source"
    render_folder = "rendered_docs"
    Dir.chdir("../") do
        FileUtils.copy_entry source_folder, render_folder
    end
end

lane :sync_files_to_readme do
    Dir.chdir("../") do
        sh "rdme docs rendered_docs --version\=4.0 --key\=#{ENV['secrets.README_API_KEY']}", log: false
    end
end

def render_markdown_file(file)
    sh "embedme", "#{file}", "--strip-embed-comment", "--stdout", "> #{file}.md"
end
