name: Build Android project 🤖

on:
  push

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Grant execute permission for gradlew
        working-directory: ./projects/android/
        run: chmod +x gradlew

      - name: Assemble App APK
        working-directory: ./projects/android/
        run: ./gradlew assembleDebug
  