name: Check docs ✅

on:
  push
  pull_request

jobs:
  embed_code:
    name: Checking docs are safe to merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install gem dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install
      - run: bundle exec fastlane bootstrap
      - run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
      - run: |
          bundle exec fastlane check_docs
