name: Sync to Readme

on:
  push:
    branches:
      - testing-sync

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'sync/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Run GitHub Action to sync docs in `documentation` directory
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: docs rendered_docs --key=${{ secrets.README_API_KEY }} --version=v5.0